### ISSUE TITLE
Heyy hii , am working on an app using flutter local notification , am trying to add buttons to it but am getting errors when I click it , can U please help me to solve it ?

### ISSUE THREAD

**Issue by ampro88** [Rono0365/freshfit#3]

**Comment by Rono0365** [comment]
hey @ampro88 could you emphasize more on the problem ,I might help you solve it

**Comment by ampro88** [comment]
D/EGL_emulation(20325): eglCreateContext: 0xf21dd270: maj 2 min 0 rcv 2
D/EGL_emulation(20325): eglCreateContext: 0xf21e44a0: maj 2 min 0 rcv 2
D/HostConnection(20325): HostConnection::get() New Host Connection established 0xf21ddb30, tid 20422
D/HostConnection(20325): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
D/EGL_emulation(20325): eglMakeCurrent: 0xf21e44a0: ver 2 0 (tinfo 0xbec6b790) (first time)
D/AndroidRuntime(20325): Shutting down VM
E/AndroidRuntime(20325): FATAL EXCEPTION: main
E/AndroidRuntime(20325): Process: com.radioApp.radio_app, PID: 20325
E/AndroidRuntime(20325): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(20325): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4041)
E/AndroidRuntime(20325): 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
E/AndroidRuntime(20325): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
E/AndroidRuntime(20325): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20325): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(20325): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(20325): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20325): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(20325): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(20325): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(20325): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:421)
E/AndroidRuntime(20325): 	at java.lang.String.valueOf(String.java:2924)
E/AndroidRuntime(20325): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(20325): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:175)
E/AndroidRuntime(20325): 	at com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver.startEngine(ActionBroadcastReceiver.java:87)
E/AndroidRuntime(20325): 	at com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver.onReceive(ActionBroadcastReceiver.java:65)
E/AndroidRuntime(20325): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4032)
E/AndroidRuntime(20325): 	... 8 more
I/Process (20325): Sending signal. PID: 20325 SIG: 9
Lost connection to device.

**Comment by ampro88** [comment]
Its kind of difficult to explain here , can u please connect in discord or google meet to help me ? so I can share my screen and explain it to you

**Comment by ampro88** [comment]
I have added a button to local notification and I am getting this error when I click it
